export const CONFIG = {
  CONTEXT: {
    MAX_TOKENS: 128000,
    COMPRESSION_THRESHOLD: 0.75,
    SIZE_THRESHOLD: 2000,
  },
  VERIFICATION: {
    MAX_ITERATIONS: 3,
    CONFIDENCE_THRESHOLD: 0.8,
    MIN_RESULT_LENGTH: 50,
    MAX_SINGLE_BLOCK_LENGTH: 200,
    LONG_RESULT_THRESHOLD: 500,
    SHORT_RESULT_PENALTY: 0.2,
    LONG_RESULT_BONUS: 0.1,
    MIN_FULL_CONTENT_LENGTH: 200,
  },
  RLM: {
    CHUNK_SIZE: 50000,
    MAX_CONCURRENT: 5,
    RECURSION_DEPTH: 3,
  },
  POSITION: {
    START_WEIGHT: 1.0,
    MIDDLE_WEIGHT: 0.5,
    END_WEIGHT: 0.95,
    MAX_MIDDLE_RATIO: 0.3,
  },
  OPENSAGE: {
    TASK_HISTORY_LIMIT: 10,
    MIN_MULTI_STEP_LENGTH: 100,
    COST_MULTIPLIER: 0.01,
    BASE_LATENCY_MS: 5000,
    ENSEMBLE_LATENCY_MS: 8000,
  },
} as const;

export const VERIFICATION_CONFIDENCE_THRESHOLD = CONFIG.VERIFICATION.CONFIDENCE_THRESHOLD;

export const CLARIFICATION_CONFIDENCE_THRESHOLD = 0.5;
